export const randomPrompts = {
  text: [
    "Create a comprehensive guide for starting a sustainable urban garden",
    "Develop a creative marketing strategy for a local coffee shop using social media",
    "Write a technical documentation for a REST API authentication system",
    "Design a user onboarding flow for a productivity mobile application",
    "Analyze market trends for electric vehicles in emerging economies",
    "Create an engaging email newsletter template for a fitness coaching business",
    "Develop a crisis communication plan for a small technology startup",
    "Write a compelling product description for an eco-friendly water bottle",
    "Design a customer feedback system for an e-commerce platform",
    "Create a content calendar for a personal finance education blog",
    "Develop a training program for remote team collaboration",
    "Write a proposal for implementing AI chatbots in customer service",
    "Design a reward system for a mobile gaming application",
    "Create a social media strategy for promoting mental health awareness",
    "Develop a workflow optimization plan for a creative agency",
    "Write a comprehensive review of emerging blockchain technologies",
    "Design an accessibility audit checklist for web applications",
    "Create a brand storytelling framework for artisan food producers",
    "Develop a data visualization strategy for quarterly business reports",
    "Write a user research methodology for understanding customer behavior"
  ],
  image: [
    "A futuristic cityscape at sunset with flying cars and neon lights",
    "Portrait of a wise old wizard with glowing eyes and mystical aura",
    "Minimalist logo design for a sustainable technology startup",
    "Abstract art representing digital transformation and innovation",
    "Product photography of a luxury smartwatch on marble surface",
    "Cozy coffee shop interior with warm lighting and vintage furniture",
    "Majestic mountain landscape with aurora borealis in the night sky",
    "Cyberpunk street scene with holographic advertisements",
    "Elegant fashion model in avant-garde clothing against urban backdrop",
    "Underwater scene with colorful coral reef and tropical fish",
    "Steampunk mechanical dragon with intricate brass details",
    "Modern architectural building with glass and steel geometric design",
    "Fantasy forest with magical creatures and glowing mushrooms",
    "Vintage car on a desert highway during golden hour",
    "Space station orbiting Earth with astronauts in the background",
    "Japanese garden with cherry blossoms and traditional bridge",
    "Post-apocalyptic wasteland with abandoned buildings and overgrown vegetation",
    "Luxury yacht sailing in crystal clear tropical waters",
    "Medieval castle on a cliff overlooking stormy seas",
    "High-tech laboratory with scientists working on advanced experiments"
  ],
  video: [
    "Time-lapse of a flower blooming from seed to full blossom in spring garden",
    "Cinematic trailer for a sci-fi adventure featuring space battles and alien worlds",
    "Step-by-step cooking tutorial showing how to make authentic Italian pasta",
    "Animated logo reveal with particle effects and dynamic typography",
    "Documentary-style interview setup with professional lighting and multiple camera angles",
    "Drone footage flying through a misty forest at dawn",
    "Product demonstration video showcasing a new smartphone's features",
    "Fashion runway show with models walking in slow motion",
    "Behind-the-scenes footage of a movie production with crew and equipment",
    "Workout routine video with energetic music and multiple exercise demonstrations",
    "Travel vlog exploring ancient temples in Southeast Asia",
    "Corporate presentation with animated charts and professional transitions",
    "Music video with synchronized dance choreography and colorful lighting",
    "Educational explainer video about renewable energy with animated graphics",
    "Sports highlight reel with dramatic slow-motion replays",
    "Art creation process showing a painter working on a large canvas",
    "Technology review video comparing different laptop models",
    "Wedding ceremony footage with emotional moments and beautiful scenery",
    "Gaming livestream with commentary and viewer interaction",
    "Virtual tour of a luxury real estate property with smooth camera movements"
  ],
  editing: [
    "Remove background from product photo using AI and replace with studio gradient",
    "Enhance portrait photo using AI to improve skin tone and remove blemishes",
    "Automatically color grade sunset footage to achieve cinematic orange and teal look",
    "Use AI to generate smooth transitions between video clips with motion blur",
    "Apply AI-powered noise reduction and sharpening to low-light photography",
    "Automatically remove unwanted objects from landscape photo using content-aware fill",
    "Generate realistic shadows and reflections for product placement in scene",
    "Use AI to upscale and enhance old family photos to 4K resolution",
    "Automatically stabilize shaky handheld footage and add smooth camera movements",
    "Apply AI-powered HDR tone mapping to create dramatic landscape effects",
    "Generate animated text overlays and lower thirds for interview video",
    "Use AI to match color temperature and exposure across multiple photos",
    "Automatically crop and frame video content for different social media formats",
    "Apply AI-powered beauty filters while maintaining natural appearance",
    "Generate seamless loop animations from still photographs using AI",
    "Use AI to remove audio noise and enhance voice clarity in recordings",
    "Automatically generate captions and subtitles for video content",
    "Apply AI-powered style transfer to transform photo into artistic painting",
    "Use AI to extend image borders and fill missing areas intelligently",
    "Generate realistic motion blur effects for dynamic action photography"
  ]
};

export const getRandomPrompt = (category: 'text' | 'image' | 'video' | 'editing' = 'text'): string => {
  const prompts = randomPrompts[category];
  return prompts[Math.floor(Math.random() * prompts.length)];
};