services:
  backend:
    image: node
    container_name: llm-backend
    working_dir: /app
    volumes:
      - ./back:/app
      - /app/node_modules
    env_file:
      - ./back/.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped

  frontend:
    image: node
    container_name: llm-frontend
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    env_file:
      - ./front/.env
    ports:
      - "8090:8090"
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
