services:
  mongodb:
    image: mongo
    container_name: llm-mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - llm_network
    restart: unless-stopped

  backend:
    image: node
    container_name: llm-backend
    working_dir: /app
    volumes:
      - ./back:/app
      - /app/node_modules
    env_file:
      - ./back/.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - llm_network

  frontend:
    image: node
    container_name: llm-frontend
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    env_file:
      - ./front/.env
    ports:
      - "8090:8090"
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
    networks:
      - llm_network

networks:
  llm_network:
    driver: bridge

volumes:
  mongodb_data:
